### ISSUE TITLE
something wrong with ListView

### ISSUE THREAD

**Issue by r3d9u11** [haxeui/haxeui-html5#17]
## Expected Behavior
simple page with one ListView

## Current Behavior
blank page
![err2](https://cloud.githubusercontent.com/assets/15020827/23611988/9082d880-028a-11e7-8183-b64a7fa089fd.png)

## Test app / minimal test case
[sample](https://github.com/r3d9u11/haxe-basics/tree/master/9_AdditionalLibraries/9.4_GuiFrameworks/9.4.2_HaxeUI/9.4.2.4_haxeui-html5/9.4.2.4.1_Components/ListView)

## Your Environment
Linux Mint 18.1 x64
Haxe 3.4.0
haxeui-core from git
haxeui-html5 from git
Firefox 51.0.1

Thanks.

**Comment by aW4KeNiNG** [comment]
Can you try to add `contentWidth`?

`<listview width="300" height="100%" contentWidth="100%">`?

**Comment by r3d9u11** [comment]
tried just now, but it doesn't effect

**Comment by r3d9u11** [comment]
@aW4KeNiNG can you check does it working for you?

**Comment by ianharrigan** [comment]
I'll be back on Sunday also, so I can try then

**Comment by ianharrigan** [comment]
Can this be retested? I did make a fix, but im not sure its related. Your app (like the dropdown) works fine for me... 

![image](https://cloud.githubusercontent.com/assets/3024242/24469959/90db74d2-14bd-11e7-8641-7b4d31f39ed0.png)

**Comment by ianharrigan** [comment]
Ok, i think ive found it. I seems the following styles need to in the index.html:

```css
* {
    box-sizing: border-box;
}

html {
    margin: 0;
    width: 100%;
    height: 100%;
}

body {
    font-family: 'Arial';
    font-size: 13px;
    margin: 0;
    width: 100%;
    height: 100%;
}
```

Ill open a new issue about this, but can close if it works for you. 

Cheers,
Ian
