### ISSUE TITLE
something wrong with DropDown

### ISSUE THREAD

**Issue by r3d9u11** [haxeui/haxeui-html5#18]
## Expected Behavior
simple page with one DropDown. menu must be displayed after DropDown clicked

## Current Behavior
menu was displayed out of page
![err1](https://cloud.githubusercontent.com/assets/15020827/23612134/447103d0-028b-11e7-86e6-44fec2025cb2.png)

## Test app / minimal test case
[sample](https://github.com/r3d9u11/haxe-basics/tree/master/9_AdditionalLibraries/9.4_GuiFrameworks/9.4.2_HaxeUI/9.4.2.4_haxeui-html5/9.4.2.4.1_Components/DropDown)

## Your Environment
Linux Mint 18.1 x64
Haxe 3.4.0
haxeui-core from git
haxeui-html5 from git
Firefox 51.0.1

Thanks.

**Comment by ianharrigan** [comment]
Can we retest this? It works fine for me (your sample from your repo)

**Comment by ianharrigan** [comment]
![image](https://cloud.githubusercontent.com/assets/3024242/24469685/97f8872e-14bc-11e7-9c6a-bacad91fb271.png)

**Comment by ianharrigan** [comment]
Ok, i think ive found it. I seems the following styles need to in the index.html:

```css
* {
    box-sizing: border-box;
}

html {
    margin: 0;
    width: 100%;
    height: 100%;
}

body {
    font-family: 'Arial';
    font-size: 13px;
    margin: 0;
    width: 100%;
    height: 100%;
}
```

Ill open a new issue about this, but can close if it works for you. 

Cheers,
Ian
