### ISSUE TITLE
Certain css styles need to be present in hosting .html file

### ISSUE THREAD

**Issue by ianharrigan** [haxeui/haxeui-html5#19]
Currently, the following styles my be in the .html file in order for the UI to work correctly:

```css
* {
    box-sizing: border-box;
}

html {
    margin: 0;
    width: 100%;
    height: 100%;
}

body {
    font-family: 'Arial';
    font-size: 13px;
    margin: 0;
    width: 100%;
    height: 100%;
}
```

## Expected Behavior
This should happen automatically (not the exact styles, investigation needs to go into which are the minimum / best ones) 

## Current Behavior
If you dont include these styles then measurement issues arise, which usually, means you dont end up with a visible UI

## Possible Solution
A configurable flag somewhere in the backend (defaults to true) that add the most important of these properties automatically.
